---
Standards:
  -
    Title: Compute & Execution Models - How Code Runs in the Cloud
    Description: "Intro to Cloud Computing, The Compute Spectrum: Control versus Abstraction, Scaling Models: How Systems Respond to Load"
    UID: 0789535f-a9f2-4af9-95b4-071cc2de9d05
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 5a1bfc16-d91c-4e28-bf85-d481239904f1
        Path: /compute-and-execution-models/intro-to-cloud-computing.md
      -
        Type: Lesson
        UID: d51fc892-a00c-4709-8f8e-0c02e8db332d
        Path: /compute-and-execution-models/the-compute-spectrum.md
      -
        Type: Lesson
        UID: fbbacab6-45da-4dfe-9b90-1fe210b17997
        Path: /compute-and-execution-models/scaling-models.md